canvas:
  height: 100
  radius: 125
teleportHeight: 200
cooldownMs: 60000

worldName: "mplace_world"

redis:
  host: "127.0.0.1"
  port: 6379

mongo:
  host: "127.0.0.1"
  port: 27017
  database: "mplace"
  username: "admin"
  password: "12345"
